---
title: "Breed standardize"
author: "Alyssa Vanderbeek (amv2187)"
date: "11/19/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

theme_set(theme_bw())
```

```{r}
dog_bite = read_csv('~/Desktop/DOHMH_Dog_Bite_Data.csv',
                    col_type = cols(UniqueID = col_integer(),
                        DateOfBite = col_date(format = '%B %d %Y'), # set as date variable
                        Species = col_character(),
                        Breed = col_character(),
                        Age = col_number(),
                        Gender = col_character(),
                        SpayNeuter = col_logical(),
                        Borough = col_character(),
                        ZipCode = col_character()
                      )) %>% # read data
  janitor::clean_names() %>%
  mutate(pit_bull = str_detect(tolower(breed), 'pit bull|pitbull|pit-bull')) # logical column for whether dog was a pitbull breed or not

# dog bites in 2016 only (to match to licensing data)
dg_2016 = dog_bite %>%
  filter(date_of_bite > '2016-01-01' & date_of_bite < '2016-12-31')
```

```{r}
# point plot of all dog bites in data
dog_bite %>%
  group_by(borough, pit_bull) %>% # group by borough and whether the dog was a pit bull or not
  count %>% # get total counts
  ungroup %>%
  spread(key = pit_bull, value = n) %>% # spread to calculate percentage of bites that were given by pit bulls
  mutate(total_bites = `FALSE` + `TRUE`, # column of total number of bites
         pct_pb_bites = `TRUE` / total_bites, # percentage of bites that are from pit bulls
         borough = fct_reorder(borough, total_bites, .desc = T)) %>% # factor and order borough by total number of bites
  ggplot(aes(x = borough, y = total_bites)) +
  geom_point(aes(size = pct_pb_bites)) + # change size of plotted points by the percentage of the bites that were given by pit bulls
  labs(title = 'Dog bites in NYC (2015-2018)',
       x = 'Borough',
       y = 'Number of dog bites',
       size = 'Percentage of pit bull bites') +
  scale_y_continuous(limits = c(0, 2500)) +
  theme(legend.position = 'bottom')


# stacked bar plot for 2016 only (to be matched with licensing data)
dg_2016 %>%
  ggplot(aes(x = borough, fill = pit_bull)) +
  geom_bar() + 
  viridis::scale_fill_viridis(
    name = 'Dog breed',
    labels = c('Other', 'Pit Bull'),
    discrete = T
  )


```

