---
title: "Data cleaning/prep"
author: "Alyssa Vanderbeek"
date: "11/27/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(zipcode)

```

## Dog Bite data


```{r}
data(zipcode) 
zipcode = zipcode %>%
  filter(city %in% c('New York', 'Bronx', 'Brooklyn', 'Queens', 'Staten Island'))

zip_list = zipcode %>%
  select(city, zip) %>%
  nest(-city)
```


```{r}
# list of official NYC zip codes 
nyc.official.zip <- read_csv("./data/Demographic_Statistics_By_Zip_Code.csv") %>%
  janitor::clean_names() %>% 
  rename(official_zip = jurisdiction_name) %>%
  select(official_zip) %>%
  unlist %>%
  unname %>%
  paste(., collapse = '|')

official.zip = paste(zipcode$zip, collapse = '|')

# dog bite data
dog_bite = read_csv('./data/DOHMH_Dog_Bite_Data.csv',
                    col_type = cols(UniqueID = col_integer(),
                        DateOfBite = col_date(format = '%B %d %Y'), # set as date variable
                        Species = col_character(),
                        Breed = col_character(),
                        Age = col_number(),
                        Gender = col_character(),
                        SpayNeuter = col_logical(),
                        Borough = col_character(),
                        ZipCode = col_character()
                      )) %>% # read data
  janitor::clean_names() %>%
  mutate(pit_bull = str_detect(tolower(breed), 'pit bull|pitbull|pit-bull')) %>% # logical column for whether dog was a pitbull breed or not
  mutate(
    zip_code = zip_code %>% 
               ifelse(str_length(.) != 5, NA, .) %>%  # set zip codes without length 5 equal to NA
               str_replace(., "O", "0") %>% # replace O's with zeros
               ifelse(str_detect(., "^[02-9]"), NA, .), # ?
    zip_match = str_detect(zip_code, official.zip), # is the given zip code valid?
    zip_code  = ifelse(zip_match == FALSE, NA, zip_code)
  ) %>%
  left_join(.,
            na.omit(.) %>% 
            left_join(., count(., borough), by = "borough") %>% 
            group_by(borough, zip_code) %>%
            summarize(proportion = n()/unique(n)) %>% 
            rename(zip_list = zip_code) %>%
            nest(zip_list, proportion) %>% rename(zip_nest = data)) %>% 
  mutate(
    zip_sample = map_chr(.x = zip_nest, ~sample(.x$zip_list, 1, prob = .x$proportion)),
    zip_code_imputed = zip_code %>% ifelse(is.na(.), zip_sample, .)
  ) %>% 
  select(-c(zip_nest, zip_sample))

write.csv(dog_bite, './data/dog_bite.csv', row.names = F)
```


## Licensing data

```{r}
license_df <- read_csv("./data/NYC_Dog_Licensing_Dataset.csv") %>%
  mutate(Borough = tolower(Borough),
         LicenseIssuedDate = as.Date(LicenseIssuedDate, "%m/%d/%Y"),
         LicenseExpiredDate = as.Date(LicenseExpiredDate, "%m/%d/%Y"),
         issued_year = year(LicenseIssuedDate),
         expired_year = year(LicenseExpiredDate),
         cleaned_borough = Borough)

misassigned_queens <- c("astoria", "elmhurst", "flushing", "jackson heights", "kew gardens", "woodside", "briarwood", "corona", "forest hills", "ozone park", "richmond hill", "rockaway park", "arverne", "bayside", "belle harbor", "cambria heights", "college point", "east elmhurst", "glen oaks", "glendale", "jackson hgts", "long island city", "maspeth", "middle vilg", "middle village", "oakland gardens", "quens", "ridgewood", "so richmond", "south richmond hil", "woodside ny.", "fresh meadows")

misassigned_nyc <- c("jersey city", "albany", "bronxville", "floral park", "hoboken", "kissimmee florida", "lynbrook", "middletown", "san francisco", "santa monica", "wappingers falls, ny", "west palm beach", "the villages")

recode_staten_island <- c("staten is", "staten island, ny", "staten island")

unknown_borough <- c("new york", "new york city", "nyc", "ny", "b", "potomac", NA)

unknown_borough_df <- license_df %>%
  filter(cleaned_borough == "unknown") %>%
  select(RowNumber, ZipCode, cleaned_borough)

zip_code_borough <- read_csv("./zelos/zip_codes_borough.csv")

license_df <- license_df %>%
  mutate(cleaned_borough = ifelse(cleaned_borough %in% misassigned_queens, "queens", cleaned_borough),
         cleaned_borough = ifelse(cleaned_borough %in% misassigned_nyc, "not nyc", cleaned_borough),
         cleaned_borough = ifelse(cleaned_borough %in% recode_staten_island, "staten", cleaned_borough),
         cleaned_borough = ifelse(cleaned_borough %in% unknown_borough, "unknown", cleaned_borough))

license_df <- left_join(license_df, zip_code_borough)

counts_df <- license_df %>%
  select(RowNumber, BreedName, ZipCode, Borough, cleaned_borough, supposed_borough, issued_year, expired_year)

agree_ids <- counts_df$RowNumber[which(counts_df$cleaned_borough == counts_df$supposed_borough)]

agreed_df <- counts_df %>%
  filter(RowNumber %in% agree_ids) %>%
  mutate(BreedName = tolower(BreedName))

problematic_df <- counts_df %>%
  filter(!RowNumber %in% agree_ids)

#View(problematic_df)
#write.csv(problematic_df, "problematic_ids.csv", row.names = FALSE)
```

