---
title: "Final Project Proposal"
author: "Quinton Neville, Alyssa Vanderbeek, Lyuou Zhang, Zelos Zhu"
date: "November 8, 2018"
header-includes: 
  \usepackage{graphicx}
  \usepackage{float}
  \usepackage{amsmath}
output:
   github_document
---

####1. Team Members 

- Quinton Neville, *qn2119*
- Alyssa Vanderbeek, *amv2187*
- Lyuou Zhang, *lz2586*
- Zelos Zhu, *zdz2101*

####2. Anticipated Title, Motivation, and Data

**Title** *I thought you said your dog did not bite!*

**Motivation** Pit bulls have a historically poor reputation as an aggressive breed. But in recent years, there's been a push to change this stigma. Based on the occurrence of dog bites, can we see whether pit bulls are more aggressive than other breeds, and whether this has changed over time?

**Data** Dog bite data (https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg) and dog licensing data (https://data.cityofnewyork.us/Health/NYC-Dog-Licensing-Dataset/nu7n-tubp).


####3. Planned Analyses and Final Product

**Research questions:**
- Are there more bites given by pit bulls than other breeds?
  - Does this number change by borough? Over time? 
- Are there more pitbulls in certain neighborhoods?
- Do pit bulls tend to be spayed/neutered more or less often than other breeds?
- How does the number of dog bites by breed compare to the total number of registered dogs in a certain time period?

**Final product:**
A website that summarizes the results of our analysis, including visualizations (potentially come interactive plots) and summary reports. 

**Anticipated challenges:**
The data we've found is relatively clean in terms of structure, but requires some vetting of individual entries. Additionally, linking the two datasets we intend to use will require some thought. 



####4. Timeline

- Week of 11/9 - 11/15:
    Familiarize more with the data; expand on research questions and ideas for visualizations. Come up with a single and more detailed report that summarizes the above.

- Week of 11/16 - 11/22:
    Agree on how to split up work and organize collaboration; clean data; get preliminary versions of visualizations. Discuss website skeleton.

- Week of 11/23 - 11/29:
    Build first draft of website (skeleton and populate). Layout of screencast. Finalize visualizations.

- Week of 11/30 - 12/6:
    Record screencast. Finalize products.
    