---
title: "dog_denominators_zz"
author: "Zelos Zhu"
date: "11/19/2018"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(zipcode)

license_df <- read_csv("./data/NYC_Dog_Licensing_Dataset.csv")

license_df <- license_df %>%
  mutate(Borough = tolower(Borough),
         LicenseIssuedDate = as.Date(LicenseIssuedDate, "%m/%d/%Y"),
         LicenseExpiredDate = as.Date(LicenseExpiredDate, "%m/%d/%Y"),
         issued_year = year(LicenseIssuedDate),
         expired_year = year(LicenseExpiredDate),
         cleaned_borough = Borough)

misassigned_queens <- c("astoria", "elmhurst", "flushing", "jackson heights", "kew gardens", "woodside", "briarwood", "corona", "forest hills", "ozone park", "richmond hill", "rockaway park", "arverne", "bayside", "belle harbor", "cambria heights", "college point", "east elmhurst", "glen oaks", "glendale", "jackson hgts", "long island city", "maspeth", "middle vilg", "middle village", "oakland gardens", "quens", "ridgewood", "so richmond", "south richmond hil", "woodside ny.", "fresh meadows", "sunnyside", "whitestone", "little neck", "rego park", "saint albans", "springfield gardens", "howard beach", "south richmond hill", "south ozone park", "woodhaven","rosedale", "hollis", "bellerose", "queens village", "jamaica", "far rockaway", "breezy point")

misassigned_nyc <- c("jersey city", "albany", "bronxville", "floral park", "hoboken", "kissimmee florida", "lynbrook", "middletown", "san francisco", "santa monica", "wappingers falls, ny", "west palm beach", "the villages")

recode_staten_island <- c("staten is", "staten island, ny", "staten island")

unknown_borough <-c("new york", "new york city", "nyc", "ny", "b", "potomac", NA)

license_df <- license_df %>%
  mutate(cleaned_borough = ifelse(cleaned_borough %in% misassigned_queens, "queens", cleaned_borough),
         cleaned_borough = ifelse(cleaned_borough %in% misassigned_nyc, "not nyc", cleaned_borough),
         cleaned_borough = ifelse(cleaned_borough %in% recode_staten_island, "staten", cleaned_borough),
         cleaned_borough = ifelse(cleaned_borough %in% unknown_borough, "unknown", cleaned_borough))


unknown_borough_df <- license_df %>%
  filter(cleaned_borough == "unknown") %>%
  select(RowNumber, ZipCode, cleaned_borough)

data("zipcode")
zip_code_borough <- zipcode  %>%
  rename(ZipCode = zip,
         supposed_borough = city) %>%
  select(ZipCode, supposed_borough) %>%
  mutate(ZipCode = as.numeric(ZipCode),
         supposed_borough = tolower(supposed_borough),
         supposed_borough = ifelse(supposed_borough %in% misassigned_queens, "queens", supposed_borough),
         supposed_borough = ifelse(supposed_borough %in% misassigned_nyc, "not nyc", supposed_borough),
         supposed_borough = ifelse(supposed_borough %in% recode_staten_island, "staten", supposed_borough)) %>%
  filter(ZipCode %in% license_df$ZipCode)

license_df <- left_join(license_df, zip_code_borough, by = "ZipCode")

counts_df <- license_df %>%
  select(RowNumber, AnimalGender, BreedName, ZipCode, Borough, cleaned_borough, supposed_borough, LicenseIssuedDate, LicenseExpiredDate, issued_year, expired_year)

#what to do with these odd cases ~ 140 of them
counts_df %>%
  group_by(ZipCode, Borough, cleaned_borough, supposed_borough) %>%
  View()

agree_ids <- counts_df$RowNumber[which((counts_df$cleaned_borough  == counts_df$supposed_borough)|
                                       (counts_df$cleaned_borough == "manhattan" & counts_df$supposed_borough == "new york"))]
agreed_df <- counts_df %>%
  filter(RowNumber %in% agree_ids,
         cleaned_borough != "not nyc") %>%
  mutate(BreedName = tolower(BreedName))

problematic_df <- counts_df %>%
  filter(!RowNumber %in% agree_ids | cleaned_borough == "not nyc")

View(problematic_df)
#write.csv(problematic_df, "problematic_ids.csv", row.names = FALSE)

#All Dogs -- Based on Issued Year Zip Code
a <- agreed_df %>%
  group_by(issued_year) %>%
  count(ZipCode)

#All Dogs -- Based on Issued Year Borough
b <- agreed_df %>%
  group_by(issued_year) %>%
  count(cleaned_borough)

#PitBulls -- Based on Issued Year Zip Code
c <- agreed_df %>%
  filter(grepl("pit bull", BreedName)) %>%
  group_by(issued_year) %>%
  count(ZipCode)

#Pitbulls -- Based on Issued Year Borough
d <- agreed_df %>%
  filter(grepl("pit bull", BreedName)) %>%
  group_by(issued_year) %>%
  count(cleaned_borough)

write.csv(a, file = "./data/all_dogs_zip.csv", row.names = FALSE)
write.csv(b, file = "./data/all_dogs_borough.csv", row.names = FALSE)
write.csv(c, file = "./data/pitbulls_zip.csv", row.names = FALSE)
write.csv(d, file = "./data/pitbulls_borough.csv", row.names = FALSE)
write.csv(agreed_df, file = "./data/agreed_boroughs_license_df.csv", row.names = FALSE)
```

#My own plot I need to render
```{r}
bite_df <- read_csv("./data/dog_bite_12.4.csv")

bite_df %>%
  group_by(gender) %>%
  count() %>%
  ggplot(aes(x = gender,, y = n, fill = gender))  +
  geom_bar(stat="identity", position=position_dodge()) + 
  scale_fill_manual(values=c('#FFC0CB','#87CEEB', '#A9A9A9'))

bite_df %>%
  group_by(spay_neuter) %>%
  count() %>%
  ggplot(aes(x = spay_neuter, y = n, fill = spay_neuter))  +
  geom_bar(stat="identity", position = position_dodge()) + 
  scale_fill_manual(values=c('#B22222','#90EE90'))

bite_df %>%
  group_by(gender, spay_neuter) %>%
  count() %>%
  mutate(gender_spay = paste(gender, spay_neuter, " "))%>%
  ggplot(., aes(gender_spay, fill = interaction(gender, spay_neuter), color = gender))  +
  geom_bar(stat = "count", position = "fill") + 
  scale_fill_manual(values=c('#FFC0CB','#87CEEB', '#A9A9A9', '#FFC0CB','#87CEEB', '#A9A9A9'))


ggplot(fruit, aes(Fruit)) +
  geom_bar( aes(fill=interaction(Color,Ripe), color=Color), stat="count", position="fill")+ 
  scale_y_continuous(labels=scales::percent)+
  scale_fill_manual(values=c("pink","lightgreen","lightblue","red", "green","blue"))+
  theme_bw()
```
