---
title: "Extended Proposal"
author: "Quinton Neville, Alyssa Vanderbeek, Lyuou Zhang, Zelos Zhu"
date: "November 15, 2018"
header-includes: 
  \usepackage{graphicx}
  \usepackage{float}
  \usepackage{amsmath}
output:
   github_document
---

#### Team Members 

- Quinton Neville, *qn2119*
- Alyssa Vanderbeek, *amv2187*
- Lyuou Zhang, *lz2586*
- Zelos Zhu, *zdz2101*



### Title, Motivation, and Data

**Title** *I thought you said your dog did not bite!*

**Motivation** Pit bulls have a historically poor reputation as an aggressive breed. But in recent years, there's been a push to change this stigma. Based on the occurrence of dog bites, can we see whether pit bulls are more aggressive than other breeds, and whether this has changed over time?

**Data** [Dog bite data](https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg) and [dog licensing data](https://data.cityofnewyork.us/Health/NYC-Dog-Licensing-Dataset/nu7n-tubp) available on NYC Open Data. Google Drive containing datasets available [here](https://drive.google.com/drive/folders/1wZfIbv9UWAoI-YO1mwRgoXmU-ucr0inX).



### Research Questions

- Are there more bites given by pit bulls than other breeds?
  - Does this number change by borough? Over time? 
- Are there more pitbulls in certain neighborhoods?
- Do pit bulls tend to be spayed/neutered more or less often than other breeds?
- How does the number of dog bites by breed compare to the total number of registered dogs in a certain time period?
- Does season / weather affect the number of dog bites?



### Detailed data description

**Dog Licensing data**: Active Dog Licenses during 2016.

All dog owners residing in NYC are required by law to license their dogs. The data is sourced from the [DOHMH Dog Licensing System](https://a816-healthpsi.nyc.gov/DogLicense), where owners can apply for and renew dog licenses. Each record represents a unique dog license that was active during the year, but not necessarily a unique record per dog, since a license that is renewed during the year results in a separate record of an active license period. Each record stands as a unique license period for the dog over the course of the yearlong time frame.

Variables provided:
RowNumber,	AnimalName,	AnimalGender,	AnimalBirthMonth,	BreedName,	Borough,	ZipCode,	CommunityDistrict,	CensusTract2010,	NTA,	CityCouncilDistrict,	CongressionalDistrict,	StateSenatorialDistrict,	LicenseIssuedDate,	LicenseExpiredDate

**Dog Bite data** NYC Reported Dog Bites (2015 - 2018)

Information reported assists the Health Department to determine if the biting dog is healthy ten days after the person was bitten in order to avoid having the person bitten receive unnecessary rabies shots. Data is collected from reports received online, mail, fax or by phone to 311 or NYC DOHMH Animal Bite Unit. Each record represents a single dog bite incident. Information on breed, age, gender and spayed or neutered status have not been verified by DOHMH and is listed only as reported to DOHMH.

Variables provided:
UniqueID,	DateOfBite,	Species,	Breed,	Age,	Gender,	SpayNeuter,	Borough,	ZipCode



### Data plan

**Cleaning**

*Dog Bite data*

Impute missing zip code by the following algorithm:
(a) For each borough in the dataset, pull unique zip codes. 
(b) Assign equal probability to each zip code per borough
(c) Match borough to missing entries
(d) Randomly assign zip code based on probabilities

Standardize breed name:
To begin, construct a binary variable for pitbull vs. other. Grep for "pit bull". Verify that there are no other permutations of pit bull breed name.

*Dog Licensing data*

Nothing to be done.

**Analysis**

See visualizations.



### Visualizations

- Heat map of number of dog bites by zip code. Use library ("leaflet") to find map of NYC area.
- Bar plot of number of pitbulls by borough (include stacked bar for number of pitbull bites/number of pitbulls). Two y-axes: (1) counts and (2) percent of all registered dogs. Alternatively, a point plot of the number of pitbulls and number of pitbull bites, where the size of points is determined by the proportion of pitbulls to total number of licensed dogs; grouped by borough.
- Line plot of number of bites over time (group by pitbull/not, borough).
- Bar plot of number of dog bites by gender, spay/neuter.



### Work assignments

Quinton: Impute zipcodes. Line plot.

Alyssa: Standardize breed name. Bar plot of number of pit bulls by borough.

Lyuou: Check relation between gender (missing) and spay/neuter. Heat map?

Zelos: Get denominators from licensing data. Bar plot of dog bites by gender, spay/neuter (if valid). 



### Timeline

- Week of 11/9 - 11/15:
    Familiarize more with the data; expand on research questions and ideas for visualizations. Come up with a single and more detailed report that summarizes the above. Agree on how to split up work and organize collaboration.

- Week of 11/16 - 11/22:
    Clean data; get preliminary versions of visualizations. Discuss website skeleton.

- Week of 11/23 - 11/29:
    Build first draft of website (skeleton and populate). Layout of screencast. Finalize visualizations.

- Week of 11/30 - 12/6:
    Record screencast. Finalize products.
    